global:
  scrape_interval: 5s

scrape_configs:
  # Flink JobManager metrics
  - job_name: 'flink-jobmanager'
    static_configs:
      - targets: ['flink-jobmanager:9249']

  # Flink TaskManager metrics
  - job_name: 'flink-taskmanager'
    static_configs:
      - targets: ['flink-taskmanager:9250']

  # Kafka metrics
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']

  # Data Generator metrics
  - job_name: 'data-generator'
    static_configs:
      - targets: ['data-generator:9091']
